""" 0389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"

Example 2:
    Input: s = "", t = "y"
    Output: "y"

Constraints:
  * 0 <= s.length <= 1000
  * t.length == s.length + 1
  * s and t consist of lowercase English letters.
"""


from collections import Counter

class Solution:
    """ Find the difference """

    def findTheDifference(self, s: str, t: str) -> str:
        """ Решение задачи """

        s_counter, t_counter = Counter(s), Counter(t)
        char, _ = list(set(t_counter.items()) - set(s_counter.items()))[0]

        return char
